### ISSUE TITLE
No normalization for n2?

### ISSUE THREAD

**Issue by ademcan** [owenjm/damid_misc#1]
Hi Owen,
In your script polii.correlation.plot you perform some normalization on the n1 samples log2 ratio but I don't see anything related to the normalization of the n2 samples. I was wondering if this was normal? 
https://github.com/owenjm/damid_misc/blob/f79a1773d6f372c6e1196e1d05d2428891e73ad0/polii.correlation.plot#L153
Thanks.

**Comment by owenjm** [comment]
Hi,
Very sorry for the late reply.  Yes, that's normal -- the (experimental) routine is designed to normalise n1 to n2, based on the expression of four housekeeping genes.  Although this seems to be informative, I would not necessarily recommend using it, or at least use with caution.

A better procedure is to apply scaling to each replicate, and I would recommend doing this unless you have a good reason not to (for example, expecting the distributions between two cells to be very different).

Hope this helps.  The correlation plot script is more designed to be a quick means of data visualisation and comparison rather than a perfect analysis.

**Comment by ademcan** [comment]
Hi, no problem. Alright, I see now, it makes more sense, thanks for the clarification.
